added missing variables
XanaduAI/xanadu-sphinx-theme pull request #24
Opened 2022-10-11 17:56 UTC by LucasSilbernagel

2022-10-11 18:51 UTC, Mandrenkov commented
Have you tried building a local version of the e.g. PennyLane documentation using this version of the XST and confirmed that the expected behaviour is happening now, @LucasSilbernagel?

2022-10-11 18:54 UTC, josh146 requested changes
Thanks @LucasSilbernagel! just two minor changes.

2022-10-11 18:54 UTC, josh146 commented on README.rst
> +
```suggestion
        "github_link": "",
```

2022-10-11 18:54 UTC, josh146 commented on README.rst
> +
until we know what this does, I would remove it 😆

2022-10-11 18:54 UTC, josh146 commented on xanadu_sphinx_theme/theme.conf
> +# Link that is opened when View on GitHub is clicked on a demo
```suggestion
# GitHub organization and repository name of associated GitHub repo.
# Used to ensure that 'View on GitHub' buttons work.
```

2022-10-11 18:56 UTC, josh146 requested changes
@LucasSilbernagel I just noticed that this variable is called `github_repo` here, not `github_link`:

https://github.com/XanaduAI/xanadu-sphinx-theme/blob/0ce956830ee6c3a9f69964164e352dc0f72b61ae/xanadu_sphinx_theme/layout.html#L298

So a few suggested changes to correct this.

2022-10-11 18:56 UTC, josh146 commented on .github/CHANGELOG.md
> +* Added missing variables: `github_link` and `gallery_dirs` to address the View on GitHub link not working for demos.
```suggestion
* Added missing variables: `github_repo` and `gallery_dirs` to address the View on GitHub link not working for demos.
```

2022-10-11 18:56 UTC, josh146 commented on README.rst
> +        "github_link": "",
```suggestion
        "github_repo": "",
```

2022-10-11 18:56 UTC, josh146 commented on README.rst
> +    ``"github_link": "Organization/repo"``.
```suggestion
``github_repo``
    The GitHub organization and repository associated with the documentation. E.g.,
    for a GitHub repository https://github.com/Organization/repo, this should be
    ``"github_repo": "Organization/repo"``.
```

2022-10-11 18:56 UTC, josh146 commented on xanadu_sphinx_theme/theme.conf
> +github_link =
```suggestion
github_repo =
```

2022-10-11 20:35 UTC, LucasSilbernagel commented
> Have you tried building a local version of the e.g. PennyLane documentation using this version of the XST and confirmed that the expected behaviour is happening now, @LucasSilbernagel?

@Mandrenkov @josh146 are there instructions somewhere on how to do that?

2022-10-11 20:38 UTC, josh146 commented
@LucasSilbernagel if you install this repository locally using pip (`pip install -e .`), then `make html-norun` on the QML website will use this branch.

2022-10-11 21:17 UTC, LucasSilbernagel commented
> @LucasSilbernagel if you install this repository locally using pip (`pip install -e .`), then `make html-norun` on the QML website will use this branch.

Thanks @josh146 ! I think something still isn't right, the View on GitHub links still don't work.

2022-10-11 22:01 UTC, josh146 commented
@LucasSilbernagel have you updated the `qml/conf.py` file to specify `'github_repo':'PennyLaneAI/qml'`?

2022-10-11 22:01 UTC, josh146 approved these changes

2022-10-11 22:08 UTC, LucasSilbernagel commented
> @LucasSilbernagel have you updated the `qml/conf.py` file to specify `'github_repo':'PennyLaneAI/qml'`?

@josh146 Ah okay, that worked! Do I need to open QML PR with that change?

2022-10-11 22:26 UTC, josh146 commented
@LucasSilbernagel yes please 🙂 Note that it won't work until we make a new release of XST. Do you mind updating the `xst/_version.py` file to reflect `0.3.2`, so that we can make a release?

2022-10-12 13:25 UTC, LucasSilbernagel commented
@josh146 version updated for release. Is there anything else we have to do here, or can this just be merged?

2022-10-12 13:56 UTC, josh146 commented
Should be good to be merged @LucasSilbernagel :)

2022-10-12 13:58 UTC, merged