Update footer and navbar to match PennyLane website
XanaduAI/xanadu-sphinx-theme pull request #40
Opened 2023-09-20 14:25 UTC by Mandrenkov

**Context:**

The PennyLane website is updating the styling of its footer and navbar. Since the [PennyLane Sphinx Theme](https://github.com/PennyLaneAI/pennylane-sphinx-theme) inherits the structure and style of the Xanadu Sphinx Theme, the updated layout, configuration, etc. are also reflected here.

**Description of the Change:**

Updated the footer and navbar configuration and styles to match the new PennyLane website. The changes to the theme configuration are documented in the diff of the `README.rst`.

<details><summary>Navbar</summary>
<p>

<img width="832" alt="Navbar" src="https://github.com/XanaduAI/xanadu-sphinx-theme/assets/5883774/b7c46e42-b415-4ee0-8d4a-e98b06ba8f7d">

</p>
</details> 

<details><summary>Footer</summary>
<p>

<img width="964" alt="Footer" src="https://github.com/XanaduAI/xanadu-sphinx-theme/assets/5883774/e1f80cad-d3a1-4bc3-9c32-633d98688391">

</p>
</details> 

<details><summary>Mobile Navbar</summary>
<p>

<img width="419" alt="Mobile Navbar Expanded" src="https://github.com/XanaduAI/xanadu-sphinx-theme/assets/5883774/f30d37c2-c9d3-455c-94c5-caae8b43ba98">

<img width="417" alt="Mobile Navbar ToC Expanded" src="https://github.com/XanaduAI/xanadu-sphinx-theme/assets/5883774/5916e31b-9275-4076-ab06-ec625ea03eaa">

</p>
</details> 

<details><summary>Mobile Footer</summary>
<p>

<img width="416" alt="Mobile Footer" src="https://github.com/XanaduAI/xanadu-sphinx-theme/assets/5883774/f047ca75-53e8-476f-bb5a-a53383528f8f">

</p>
</details> 

**Benefits:**

* The navbar and footer on the PennyLane Docs pages will be consistent with the main PennyLane website.

**Possible Drawbacks:**

* Xanadu OSS projects which do not fall under the PennyLane umbrella will adopt the appearance of the footer and navbar on the PennyLane website if they update their dependency on the Xanadu Sphinx Theme.
* Some accessibility features were compromised in the adoption of the new footer and navbar styles. These will be reinstated (and improved!) in a future patch release.

**Related GitHub Issues:**

None.

2023-09-20 14:28 UTC, Mandrenkov commented on .github/CHANGELOG.md
> +  [#33](https://github.com/XanaduAI/xanadu-sphinx-theme/pull/33)
```suggestion
  [#40](https://github.com/XanaduAI/xanadu-sphinx-theme/pull/40)
```

2023-09-20 16:08 UTC, Lorraine-at-Xanadu requested changes
Hey @Mandrenkov! You've done an incredible job matching the navbar in Sphinx. 

1. Learn > Glossary: Link is broken and should go to https://pennylane.ai/qml/glossary
2. When I hover on 'Learn' (for example) and then hover on 'Documentation' there's a delay when the 'Learn' menu closes causing overlap. 

![image](https://github.com/XanaduAI/xanadu-sphinx-theme/assets/112511934/7ccfcbe1-9c0c-4463-b727-01c98a5fc353)

2023-09-20 18:02 UTC, Mandrenkov commented
Thanks for the review, @Lorraine-at-Xanadu!

> 1. Learn > Glossary: Link is broken and should go to https://pennylane.ai/qml/glossary

I assume this is meant for the PennyLane Sphinx Theme PR: https://github.com/PennyLaneAI/pennylane-sphinx-theme/pull/29.

> 2. When I hover on 'Learn' (for example) and then hover on 'Documentation' there's a delay when the 'Learn' menu closes causing overlap.

I've updated the navbar so that the dropdown menus instantly close when a user stops hovering over it.

2023-09-20 18:03 UTC, Mandrenkov commented
Thanks for the review, @LucasSilbernagel!

> The accessibility issues are really painful

I agree the accessibility of the new navbar and footer leave much to be desired. We'll tackle it soon!

2023-09-20 18:08 UTC, LucasSilbernagel commented
> I've updated the navbar so that the dropdown menus instantly close when a user stops hovering over it.

@Mandrenkov @Lorraine-at-Xanadu this is really annoying for users with accessibility requirements and defeats the purpose of [the accessible example we followed](https://www.w3.org/WAI/tutorials/menus/flyout/#flyoutnavkbbtn) ☹️

2023-09-20 19:09 UTC, josh146 approved these changes
I didn't review the code, but reviewed the PR preview. Looks and works great @Mandrenkov, super impressed how much you got it to match!

2023-09-20 23:58 UTC, Mandrenkov commented
@LucasSilbernagel, after a discussion with @Anakhom and @AndrewGardhouse offline, we decided to reinstate the one-second delay but ensure that only one dropdown from the navbar is displayed at any given time.

2023-09-21 20:45 UTC, ashishks0522 approved these changes

2023-09-22 14:18 UTC, merged